export default {
    ON_UPDATE_HOME_DETAILS:'ON_UPDATE_HOME_DETAILS',
    ON_NAVIGATION_CLICK : 'ON_NAVIGATION_CLICK',
    ON_SELECT : 'ON_SELECT',
    ON_DESELECT : 'ON_DESELECT',
    ON_DELETE : 'ON_DELETE',
    ON_SUBMIT : 'ON_SUBMIT'
}
